### ISSUE TITLE
404 on link to the live testing iso

### ISSUE THREAD

**Issue by chpill** [fiendish/The-Debian-Gotham-Needs#3]
Opening this links to the live iso returns 404 to me https://get.debian.org/cdimage/unofficial/non-free/cd-including-firmware/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-gnome+nonfree.iso ([here in the index.html](https://github.com/fiendish/The-Debian-Gotham-Needs/blob/d77ea784e1e0523a5174371eacd0a0cb12705222/index.html#L19))

Looking around the directory https://get.debian.org/cdimage/unofficial/non-free/cd-including-firmware/weekly-live-builds/amd64/iso-hybrid/, I can see no iso files to download... Maybe there was an issue generating the page or they have been moved somewhere else?

Thanks for this web page by the way, it was always a pain to need to have a network cable at hand when installing debian on most laptops :sweat_smile:

**Comment by fiendish** [comment]
It looks like their build failed and when that happens apparently they don't fix it and try again. :(

From https://get.debian.org/cdimage/unofficial/non-free/cd-including-firmware/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-gnome+nonfree.log : 
> AppException: Resources not available at 'https://d-i.debian.org/daily-images/amd64/daily/cdrom/'
>
> ERROR: Resources not available at 'https://d-i.debian.org/daily-images/amd64/daily/cdrom/'

**Comment by fiendish** [comment]
For now I guess we'll have to use current stable instead of testing ☹️  : https://get.debian.org/cdimage/unofficial/non-free/cd-including-firmware/10.2.0-live+nonfree/amd64/iso-hybrid/debian-live-10.2.0-amd64-gnome+nonfree.iso

**Comment by fiendish** [comment]
I just sent an email to the Debian CD team about it, so we'll see what they say. Hopefully the link will start working again in a day or so when they run the next weekly build.

Thanks for the heads up! I'll leave this open until it's resolved.

**Comment by fiendish** [comment]
It looks like the cd team has added the isos back. Thank you for the helping people use Debian!

**Comment by chpill** [comment]
Thank you for creating this project :tulip: Keep up the good work :muscle:
